

DROP TABLE JPA_LOCAL_DATE_TIME IF EXISTS;

CREATE TABLE JPA_LOCAL_DATE_TIME (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP(9),
  PRIMARY KEY (ID)
);

DROP TABLE JPA_LOCAL_TIME IF EXISTS;

CREATE TABLE JPA_LOCAL_TIME (
  ID INTEGER NOT NULL,
  LOCAL_TIME TIME,
  PRIMARY KEY (ID)
);
