CREATE TABLE JPA_LOCAL_DATE_TIME (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE JPA_LOCAL_TIME (
  ID INTEGER NOT NULL,
  LOCAL_TIME TIME,
  PRIMARY KEY (ID)
);
