EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'JPA_LOCAL_DATE_TIME')) THEN
    EXECUTE STATEMENT 'DROP TABLE JPA_LOCAL_DATE_TIME;';
END!!

CREATE TABLE JPA_LOCAL_DATE_TIME (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP,
  PRIMARY KEY (ID)
)!!

EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'JPA_LOCAL_TIME')) THEN
    EXECUTE STATEMENT 'DROP TABLE JPA_LOCAL_TIME;';
END!!

CREATE TABLE JPA_LOCAL_TIME (
  ID INTEGER NOT NULL,
  LOCAL_TIME TIME,
  PRIMARY KEY (ID)
)!!
