DROP TABLE IF EXISTS JPA_LOCAL_DATE_TIME;
CREATE TABLE JPA_LOCAL_DATE_TIME (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP(9) WITHOUT TIME ZONE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JPA_LOCAL_TIME;
CREATE TABLE JPA_LOCAL_TIME (
  ID INTEGER NOT NULL,
  LOCAL_TIME TIME(9),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JPA_OFFSET_DATE_TIME;
CREATE TABLE JPA_OFFSET_DATE_TIME (
  ID INTEGER NOT NULL,
  OFFSET_DATE_TIME TIMESTAMP(9) WITH TIME ZONE,
  PRIMARY KEY (ID)
);
