DROP TABLE IF EXISTS JPA_SUPPORT;
CREATE TABLE JPA_SUPPORT (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP(6) WITHOUT TIME ZONE,
  OFFSET_DATE_TIME TIMESTAMP(6) WITH TIME ZONE,
  LOCAL_TIME TIME(6),
  PRIMARY KEY (ID)
);
