DROP TABLE IF EXISTS JPA_LOCAL_DATE_TIME;
CREATE TABLE JPA_LOCAL_DATE_TIME (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP(6) WITHOUT TIME ZONE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JPA_LOCAL_TIME;
CREATE TABLE JPA_LOCAL_TIME (
  ID INTEGER NOT NULL,
  LOCAL_TIME TIME(6),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JPA_OFFSET_DATE_TIME;
CREATE TABLE JPA_OFFSET_DATE_TIME (
  ID INTEGER NOT NULL,
  OFFSET_DATE_TIME TIMESTAMP(6) WITH TIME ZONE,
  PRIMARY KEY (ID)
);
